# Build the Go Binary.
FROM golang:1.21.1 as build_website
ENV CGO_ENABLED 0

# Copy the source code into the container.
COPY . /build

# Build the admin binary.
WORKDIR /build/app/services/website
RUN go build


# Run the Go Binary in Alpine.
FROM alpine:3.18
RUN addgroup -g 1000 -S website && \
    adduser -u 1000 -h /build -G website -S website
COPY --from=build_website --chown=website:website /build/app/services/website/website /build/website
WORKDIR /build
USER website
CMD ["./website"]

LABEL org.opencontainers.image.title="website" \
      org.opencontainers.image.authors="Alejandra Kennedy <me@aleintech.com>" \
      org.opencontainers.image.source="https://github.com/gobridge/website" \
      org.opencontainers.image.vendor="GoBridge"
